#!/usr/bin/env python
import sys
from optparse import OptionParser

from vmstat_data import VmstatData
from vmstat_plot import VmstatPlot, LOAD_AVERAGE, CPU, MEMORY, BIO

### Main
usage = '%prog interval vmstat_log [vmstat_log]'
parser = OptionParser(usage)
(options, args) = parser.parse_args()

if len(args) < 3:
    parser.print_help()
    sys.exit(1)

interval = int(args[0])
fnames = args[1:]
for fname in fnames:
    title = fname
    cand = fname.split('.')
    if len(cand) == 1:
        output = fname + '.png'
    else:
        output = '.'.join(cand[:-1]) + '.png'

    f = open(fname, 'r')
    vd = VmstatData(VmstatData.COLUMNS)
    vd.load(f)
    vp = VmstatPlot(vd,
                    graphs=(LOAD_AVERAGE, CPU, MEMORY, BIO),
                    interval=interval,
                    title=title)
    vp.plot(output)
